version: '3.4'

services:
  zauberstein.app:
    image: ${DOCKER_REGISTRY}/zauberstein.app
    build:
      context: .
      dockerfile: frontend/Dockerfile


  zauberstein.api:
    image: ${DOCKER_REGISTRY}/zauberstein.api
    build:
      context: .
      dockerfile: backend/Dockerfile


      